---
title: "Formatting Data for Analyses"
date: "`r Sys.Date()`"
format: 
  html:
    html-table-processing: none
    toc: true
    toc-depth: 4
    toc-location: left
    number-sections: true
    code-fold: true
    code-summary: "Show Code"
    fig-cap-location: bottom
    smooth-scroll: true
    theme: flatly
    font-family: serif
    font-size: 12px
    line-height: 150%
    css: styles.css  # Reference your CSS file here
---

# Initialization
```{r include=FALSE}

require(dplyr)
require(sf)
require(sp)
require(tidyverse)
require(tidyterra)
require(terra)
require(ggplot2)
require(knitr)
require(gt)
require(scales)
require(rlang)
require(zipcodeR)
require(tidyr)
require(stringr)

```

### Importing Data
```{r include=FALSE}

# setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
base = normalizePath(file.path("..", ".."), mustWork = FALSE)  
analyses = file.path(base, "analyses")
oup = file.path(analyses, "outputs")
surv = read.csv(file.path(oup, "descriptiveKAP.csv"))
surv 

```

### New Data Frame
```{r}

psurv = surv %>%
    select(c(
  "PIGSCORRECT", "BRUCECORRECT", "CWDCORRECT", "FLUALCORRECT", "COVIDCORRECT",
  "COVIDSPILLCORRECT", "RABIESALCORRECT", "RABIESCORRECT",
  "PIGSCCORRECT", "BRUCECCORRECT", "CWDCCORRECT", "FLUALCCORRECT", "COVIDCCORRECT",
  "COVIDSPILLCCORRECT", "RABIESALCCORRECT", "RABIESCCORRECT", "TURKEYCCORRECT",
  "PIGSCERTAIN", "INTERESTCERTAIN", "BRUCECERTAIN", "noSOURCE", "CWDCERTAIN", "FLUALCERTAIN",
  "COVIDCERTAIN", "COVIDSPILLCERTAIN", "RABIESALCERTAIN", "RABIESCERTAIN", "TURKEYCERTAIN",
  "CWDALNEUTRAL", "BATSNEUTRAL", "PPEREQNEUTRAL", "EHDNEUTRAL", "DARWINNEUTRAL",
  "POPREDNEUTRAL", "POPPLANNEUTRAL", "SURVEYNEUTRAL", "VACCINENEUTRAL", "PREVALNEUTRAL",
  "DIVERSENEUTRAL", "CONSEQNEUTRAL", "CLIMATENEUTRAL", "EDREQNEUTRAL", "INFONEUTRAL",
  "HANDSONNEUTRAL"))
psurv

```

### Y/N Responses
```{r}

YNcols <- c(
  "DEGREE", "TWS", "COURSE", "SELFTITLE", "COLLECT", "HANDLE",
  "PPE", "ACCESS", "INTEREST", "LICENSE")

# Convert Yes = 1, No = 0, "Unsure" or "I prefer not to answer" = NA
for (col in YNcols) {
  psurv[[paste0(col, "bin")]] <- ifelse(surv[[col]] == "Yes", 1,
                                  ifelse(surv[[col]] == "No", 0,
                                  ifelse(surv[[col]] %in% c("Unsure", "I prefer not to answer"), NA, NA)))
}

table(psurv$DEGREEbin)
table(surv$DEGREE)
table(psurv$TWSbin)
table(surv$TWS)
table(psurv$COURSEbin)
table(surv$COURSE)
table(psurv$SELFTITLEbin)
table(surv$SELFTITLE)
table(psurv$COLLECTbin)
table(surv$COLLECT)
table(psurv$HANDLEbin)
table(surv$HANDLE)
table(psurv$PPEbin)
table(surv$PPE)
table(psurv$ACCESSbin)
table(surv$ACCESS)
table(psurv$INTERESTbin)
table(surv$INTEREST)
table(psurv$LICENSEbin)
table(surv$LICENSE)

```

### Demographic
```{r}

medianage <- median(surv$AGE, na.rm = TRUE)
medianage
psurv$AGEbin <- ifelse(surv$AGE > medianage, 1, 0)
table(psurv$AGEbin)
psurv$AGEnum <- surv$AGE


psurv$GENDERbin <- ifelse(surv$GENDER == "Male", 1,
                         ifelse(surv$GENDER == "Female", 0, NA))
table(psurv$GENDERbin)


psurv$RACEbin <- ifelse(surv$RACE == "White", 1,
                       ifelse(surv$RACE == "I prefer not to answer", NA, 0))
table(psurv$RACEbin)


psurv$INCOMEnum <- ifelse(surv$INCOME == "$0-20,000", 10000,
                     ifelse(surv$INCOME == "$20,001-30,000", 25000,
                     ifelse(surv$INCOME == "$30,001-40,000", 35000,
                     ifelse(surv$INCOME == "$40,001-50,000", 45000,
                     ifelse(surv$INCOME == "$50,001-60,000", 55000,
                     ifelse(surv$INCOME == "$60,001-70,000", 65000,
                     ifelse(surv$INCOME == "$70,001-80,000", 75000,
                     ifelse(surv$INCOME == "$80,001-90,000", 85000,
                     ifelse(surv$INCOME == "$90,001-100,000", 95000,
                     ifelse(surv$INCOME == "$100,001+", 110000, NA))))))))))

psurv$INCOMEord <- factor(surv$INCOME, ordered = TRUE, levels = c(
  "$0-20,000", "$20,001-30,000", "$30,001-40,000", "$40,001-50,000",
  "$50,001-60,000", "$60,001-70,000", "$70,001-80,000", "$80,001-90,000",
  "$90,001-100,000", "$100,001+"))

psurv$INCOMEbinmed <- ifelse(is.na(psurv$INCOMEnum), NA,
                        ifelse(psurv$INCOMEnum > 62027, 1, 0))

psurv$INCOMEbinavg <- ifelse(is.na(psurv$INCOMEnum), NA,
                        ifelse(psurv$INCOMEnum > 86225, 1, 0))
table(psurv$INCOMEbinmed)
table(psurv$INCOMEbinavg)
table(psurv$INCOMEnum)
table(psurv$INCOMEord)
table(surv$INCOME)

```

## Education & Experience
```{r}

psurv$EDUCATIONord <- factor(surv$EDUCATION, ordered = TRUE, levels = c(
  "Did not graduate high school/no GED",
  "High school graduate/GED",
  "Technical/Vocational School",
  "Some College/AA or AS (2-year degree)",
  "College Graduate/BA or BS (4-year degree)",
  "Graduate or Professional School"
))
psurv$EDUCATIONbin <- ifelse(surv$EDUCATION %in% c("College Graduate/BA or BS (4-year degree)", "Graduate or Professional School"), 1,
                       ifelse(is.na(surv$EDUCATION), NA, 0))
table(psurv$EDUCATIONord)
table(psurv$EDUCATIONbin)
table(surv$EDUCATION)


psurv$COURSETIMEord <- factor(surv$COURSETIME, ordered = TRUE, levels = c("<5 years", "5-10 years", ">10 years"))
psurv$COURSETIMEbin <- ifelse(surv$COURSETIME == "<5 years", 1,
                         ifelse(surv$COURSETIME %in% c("5-10 years", ">10 years"), 0, NA))
table(psurv$COURSETIMEord)
table(psurv$COURSETIMEbin)
 table(surv$COURSETIME)

 
psurv$BIOTIMEord <- factor(surv$BIOTIME, ordered = TRUE, levels = c(
  "<1 year", "1-5 years", "5-10 years", "10-20 years", ">20 years"))
psurv$BIOTIMEbin <- ifelse(surv$BIOTIME %in% c("10-20 years", ">20 years"), 1,
                      ifelse(surv$BIOTIME %in% c("<1 year", "1-5 years", "5-10 years"), 0, NA))
table(psurv$BIOTIMEord)
table(psurv$BIOTIMEbin)
table(surv$BIOTIME)

psurv$AFFILLIATEbin <- ifelse(surv$AFFILIATE %in% c("Federal Government", "State/Provincial Government"), 1,
                        ifelse(is.na(surv$AFFILIATE), NA, 0))
table(psurv$AFFILLIATEbin)

```


## Activities & Practices
```{r}

county_median <- median(surv$COUNTIESsel2, na.rm = TRUE)
county_median
psurv$COUNTIESbin <- ifelse(is.na(surv$COUNTIESsel2), NA,
                              ifelse(surv$COUNTIESsel2 > county_median, 1, 0))

psurv$COUNTIESnum = surv$COUNTIESsel2
table(surv$COUNTIESsel2)
table(psurv$COUNTIESbin)
table(psurv$COUNTIESnum)


psurv$PPETIMEord <- factor(surv$PPETIME, ordered = TRUE,
                            levels = c("Never (0%)", "Rarely (1%-24%)", "Sometimes (25%-75%)", 
                                       "Usually (76%-99%)", "Always (100%)"))
psurv$PPETIMEbin <- ifelse(surv$PPETIME %in% c("Usually (76%-99%)", "Always (100%)"), 1,
                      ifelse(surv$PPETIME %in% c("Never (0%)", "Rarely (1%-24%)", "Sometimes (25%-75%)"), 0, NA))

table(psurv$PPETIMEbin)
table(psurv$PPETIMEord)

psurv$STATEbin <- ifelse(surv$STATE %in% c("Alive - Not Sedated", "Alive - Sedated"), 1,
                    ifelse(surv$STATE == "Dead", 0, NA))
table(psurv$STATEbin)


psurv$FIELDnum <- as.numeric(surv$FIELD)
psurv$FIELDbin <- ifelse(is.na(surv$FIELD), NA,
                    ifelse(surv$FIELD >= 50, 1, 0))
table(psurv$FIELDnum)
table(psurv$FIELDbin)


psurv$CONTACTord <- factor(surv$CONTACT, ordered = TRUE, levels = c("Never", "Rarely", "Monthly", "Weekly", "Daily"))
psurv$CONTACTbin <- ifelse(surv$CONTACT %in% c("Weekly", "Daily", "Monthly"), 1,
                      ifelse(surv$CONTACT %in% c("Never", "Rarely"), 0, NA))
table(psurv$CONTACTord)
table(psurv$CONTACTbin)

```

## Health Knowledge

```{r}

psurv$CORRECTnum  <- surv$CORRECT
psurv$CERTAINnum <- surv$CERTAIN
psurv$CCORRECTnum <- surv$CCORRECT

psurv$CORRECT50 <- ifelse(surv$CORRECT >= (5), 1, 0)
psurv$CERTAIN50 <- ifelse(surv$CERTAIN >= (5), 1, 0)
psurv$CCORRECT50 <- ifelse(surv$CCORRECT >= (5), 1, 0)

med_correct  <- median(surv$CORRECT, na.rm = TRUE)
med_certain  <- median(surv$CERTAIN, na.rm = TRUE)
med_ccorrect <- median(surv$CCORRECT, na.rm = TRUE)
med_correct  
med_certain  
med_ccorrect 
psurv$CORRECTmed <- ifelse(surv$CORRECT >= med_correct, 1, 0)
psurv$CERTAINmed <- ifelse(surv$CERTAIN >= med_certain, 1, 0)
psurv$CCORRECTtmed <- ifelse(surv$CCORRECT >= med_ccorrect, 1, 0)

avg_correct  <- mean(surv$CORRECT, na.rm = TRUE)
avg_certain  <- mean(surv$CERTAIN, na.rm = TRUE)
avg_ccorrect <- mean(surv$CCORRECT, na.rm = TRUE)
avg_correct  
avg_certain  
avg_ccorrect 
psurv$CORRECTavg   <- ifelse(surv$CORRECT >= med_correct, 1, 0)
psurv$CERTAINavg   <- ifelse(surv$CERTAIN >= med_certain, 1, 0)
psurv$CCORRECTtavg <- ifelse(surv$CCORRECT >= med_ccorrect, 1, 0)

table(psurv$CORRECT50)
table(psurv$CERTAIN50)
table(psurv$CCORRECT50)
table(psurv$CORRECTmed) 
table(psurv$CERTAINmed)
table(psurv$CCORRECTtmed) 
table(psurv$CORRECTavg  ) 
table(psurv$CERTAINavg  ) 
table(psurv$CCORRECTtavg)

```
## Attitudes & Beliefs

```{r}

psurv$TOPICSnum   = surv$TOPICSsel2
psurv$FREEINFOnum = surv$FREEINFOsel2
psurv$SOURCEnum = surv$SOURCEsel2
table(psurv$TOPICSnum  )
table(psurv$FREEINFOnum)
table(psurv$SOURCEnum)

topics_median     <- median(surv$TOPICSsel2, na.rm = TRUE)
freeinfo_median   <- median(surv$FREEINFOsel2, na.rm = TRUE)
source_median     <- median(surv$SOURCEsel2, na.rm = TRUE)
topics_median   
freeinfo_median 
source_median   
psurv$TOPICSbin <- ifelse(is.na(surv$TOPICSsel2), NA,
                          ifelse(surv$TOPICSsel2 > topics_median, 1, 0))
psurv$FREEINFObin <- ifelse(is.na(surv$FREEINFOsel2), NA,
                            ifelse(surv$FREEINFOsel2 > freeinfo_median, 1, 0))
psurv$SOURCEbin <- ifelse(is.na(surv$SOURCEsel2), NA,
                          ifelse(surv$SOURCEsel2 > source_median, 1, 0))
table(psurv$TOPICSbin)
table(psurv$FREEINFObin)
table(psurv$SOURCEbin)

################ LIKERT ####################
attitude_items <- c("CWDAL", "BATS", "PPEREQ", "EHD", "DARWIN", 
                    "POPRED", "POPPLAN", "SURVEY", "VACCINE", 
                    "PREVAL", "DIVERSE", "CONSEQ", "CLIMATE", 
                    "EDREQ", "INFO", "HANDSON")

for (var in attitude_items) {
  psurv[[paste0(var, "ord")]] <- ifelse(surv[[var]] %in% c("Agree", "Strongly Agree"), "agree",
                                 ifelse(surv[[var]] %in% c("Disagree", "Strongly Disagree"), "disagree",
                                 ifelse(surv[[var]] == "Neutral", "neutral", NA)))
  psurv[[paste0(var, "ord")]] <- factor(psurv[[paste0(var, "ord")]],
                                        levels = c("disagree", "neutral", "agree"),
                                        ordered = TRUE)
}
for (var in attitude_items) {
  print(table(psurv[[paste0(var, "ord")]]))
}

psurv$NEUTRALnum = surv$NEUTRAL
table(psurv$NEUTRALnum)

```

# Write CSV
```{r}

summary_tables <- list()
# Export frequency tables of 3-level Likert responses
likert_vars <- grep("ord$", names(psurv), value = TRUE)
for (v in likert_vars) {
  summary_tables[[v]] <- as.data.frame(table(psurv[[v]], useNA = "ifany"))
}
# Export binarized variables by group
binary_vars <- grep("bin$|avg$|med$|50$", names(psurv), value = TRUE)
summary_tables$binary_summary <- as.data.frame(
  t(sapply(psurv[, binary_vars], function(x) table(x, useNA = "ifany")))
)
writexl::write_xlsx(summary_tables, path = file.path(oup, "processedDFS.xlsx"))

```


```{r}
#| include: false

###### Processed Responses ######
oup = file.path(analyses, "outputs")
write.csv(psurv, file.path(oup, "processedKAP.csv"), row.names = FALSE)

```

```{r}
#| echo: false

##### CSS Tables #####
# kable(RSCOUNTIES, format = "html", table.attr = "class='styled-table'", align = "c")

```

## Technical Refs

```{r bib}
#| echo: false

#### To write a bib file
# knitr::write_bib(sub("^package:", "", grep("package", search(), value=TRUE)), file='pckg.bib')

#### to display the packages within the .qmd without creating another .bib ####
knitr::write_bib(sub("^package:", "", grep("package", search(), value=TRUE)), file='')

```
