---
title: "Spatial Visualization and Exploration"
date: "`r format(Sys.Date(), '%B %d, %Y')`"
output:
  word_document:
    toc: true
    number_sections: true
    fig_caption: true
  pdf_document:
    toc: true
    number_sections: true
    fig_caption: true
    highlight: zenburn
    latex_engine: xelatex
  html_document:
    toc: true
    toc_depth: 2
    toc_float: true
    number_sections: true
    theme: readable
    highlight: tango
    code_folding: show
    fig_caption: true
    df_print: paged
editor_options:
  chunk_output_type: inline
fontsize: 10pt
mainfont: "Times New Roman"
geometry: margin=1in
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
require(tidyverse)
require(zipcodeR)
require(ggmap)
require(sf)
require(knitr)
require(dplyr)
require(tigris)
options(tigris_use_cache = TRUE)
require(ggplot2)
require(RColorBrewer)
```


### Importing Data 
```{r include=FALSE}

# ---- Set Paths ----
base     <- normalizePath(file.path("..", ".."), mustWork = FALSE)
analyses <- file.path(base, "analyses")
inp <- file.path(analyses, "inputs")
oup <- file.path(analyses, "outputs")

# ---- Load Raw Dataset ----
df <- read_csv(file.path(oup, "recodeddata.csv"))
nrow(df) # 140 responses ------
names(df)

```

# Zipcode -> County 
```{r}

df <- df %>%
  mutate(ZIPCODE = as.character(ZIPCODE)) %>%
  left_join(
    zipcodeR::zip_code_db %>%
      dplyr::select(zipcode, county, state),
    by = c("ZIPCODE" = "zipcode")) %>%
  rename(COUNTY = county) %>%
  dplyr::select(-state)

# Map of Respondents / County ----------------
alcounty <- counties(state = "AL", cb = TRUE, class = "sf") %>%
  mutate(NAME = toupper(NAME))  
dfcounty <- df %>%
  filter(!is.na(COUNTY)) %>%
  count(COUNTY, name = "Respondents")
mapcounty <- alcounty %>%
  left_join(dfcounty, by = c("NAMELSAD" = "COUNTY")) %>%
  mutate(Respondents = replace_na(Respondents, 0))
centroids <- st_centroid(mapcounty)
centroids_coords <- centroids %>%
  mutate(
    lon = st_coordinates(geometry)[, 1],
    lat = st_coordinates(geometry)[, 2])

ggcounty <- ggplot(mapcounty) +
  geom_sf(aes(fill = Respondents), color = "black", size = 1) +
 geom_text(
    data = centroids_coords,
    aes(x = lon, y = lat, label = ifelse(Respondents > 0, Respondents, "")),
    size = 3, color = "grey40") +
  scale_fill_distiller(
    palette = "YlGnBu",  # switch to 'greys' for B/W 
    direction = 1,
    name = "Respondents",
    breaks = range(mapcounty$Respondents, na.rm = TRUE),
    labels = round(range(mapcounty$Respondents, na.rm = TRUE))) +
  theme_minimal(base_size = 14) +
  labs(title = "Survey Respondents by County") +
  theme(
    legend.position = "right",
    legend.title = element_text(size = 10),
    legend.title.position = "top",
    legend.text = element_text(size = 10),
    panel.grid.major = element_blank(),
    axis.text = element_blank(),
    axis.title = element_blank(),
    plot.title = element_text(face = "bold"))
ggcounty

# Export ------
ggsave(filename = "county_respondents.pdf",plot = ggcounty, path = oup, width = 8, 
       height = 6,units = "in") # Vector PDF
ggsave(filename = "county_respondents.tif",plot = ggcounty, path = oup, width = 8, 
       height = 6,dpi = 600, units = "in") # TIFF
```


